title: Julien Humbert
description: My Personal Blog
author: Julien Humbert
logo: /static/img/avatar.png
github: https://github.com/Aluok
about: Web developer

baseurl: ""
url: ""

allowsearch: true

share:
  twitter_username: julien_humbert


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
